### ISSUE TITLE
better doc for authentication?

### ISSUE THREAD

**Issue by fuzzyami** [ownaginatious/amqp-client-cli#2]
thanks for this fine repo! I think you might want to stress that during authentication, the username and password must be passed quoted:

User: guest
Password

should really be:
User: "guest"
"Password"

**Comment by ownaginatious** [comment]
I just tested it on Linux, and it works the way the docs express, but it could be something odd about your OS. Which operating system and Python version are you using?

**Comment by fuzzyami** [comment]
apologies for the late response. here's some more info:
 the OS:

> Linux ip-10-0-1-20 4.4.0-1047-aws #56-Ubuntu SMP Sat Jan 6 19:39:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

below is a snippet of my shell from my amazon instance. its Python 2.7.12, GNU bash, version 4.3.48

> root@ip-10-0-1-20:/home/ubuntu# amqpcli send localhost 5671 exchange_a simple_message -m "Hello there" -v my_vhost -s
> User: asd
> Traceback (most recent call last):
>   File "/usr/local/bin/amqpcli", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/amqp_client_cli/main.py", line 179, in main
>     app.run()
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 652, in run
>     self.invoke(self.parse(tokens))
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 634, in invoke
>     self._main.invoke(parsed)
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 523, in invoke
>     self._subcommands[k].invoke(v)
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 519, in invoke
>     self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
>   File "/usr/local/lib/python2.7/dist-packages/amqp_client_cli/main.py", line 96, in amqp_send
>     user = input(Fore.GREEN + "User: " + Fore.RESET)
>   File "<string>", line 1, in <module>
> NameError: name 'asd' is not defined


compare with the following:

> root@ip-10-0-1-20:/home/ubuntu# amqpcli send localhost 5671 exchange_a simple_message -m "Hello there" -v my_vhost -s
> User: "asd"
> Password:
> Connecting to queue @ localhost:5671... FAILED!
> Failure reason: The AMQP connection was closed: ()

**Comment by allan-simon** [comment]
is this a python2/python3 difference , on python3 / ubuntu I got it working without the `"`

**Comment by ownaginatious** [comment]
Oh wow, I somehow missed this. Hmm... not sure. I don't think there should be any difference between Python 2 and Python 3. It could be because of the `clip.py` dependency which hasn't worked great in the past. I may update this to just use the standard `argparse` or `click` at some point.

**Comment by ownaginatious** [comment]
Should be fixed in the latest version, `0.4.1`.
