### ISSUE TITLE
Incompatible with Python 3.7

### ISSUE THREAD

**Issue by nickweedon** [ownaginatious/amqp-client-cli#3]
Needs to have Pika upgraded to >= 1.1.0 then it seems to run OK

**Comment by modul** [comment]
Can confirm on Python 3.8 as well. 

Works with Pika 1.1.0 even though amqp_client_cli has a requirement of `==0.10.0`.

**Comment by ownaginatious** [comment]
I made a new release; should be fixed now 👍
